version: '3.8'
services:
  magpie_nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    tty: true
    networks:
      - magpie-network
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static-content:/usr/share/magpie/static:ro
      - log-nginx:/var/log/nginx
  magpie_ha:
    image: haproxy:lts
    depends_on:
      - magpie_app_1
      - magpie_app_2
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "8989:8989"
    networks:
      - magpie-network
    volumes:
      - ./configs/ha/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg:ro
  magpie_postgres:
    image: postgres:12
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 7rbjTcp2FISU7YByE66xIYDcNF7PQYK9SRGFniJNSnk
      MAGPIE_DATABASES_NAME: fileserver_db
      MAGPIE_DATABASES_TEST_NAME: fileserver_db_test
      MAGPIE_DATABASES_USER: file_admin
      MAGPIE_DATABASES_PASSWORD: KLclWoEl5BoDtQVsL8RB3HIhH
      MAGPIE_DATABASES_HOST: magpie_postgres
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - data-postgres:/data/postgres
    networks:
      - magpie-network
    restart: always
  magpie_redis:
    image: redis:6-buster
    entrypoint: redis-server --rdbcompression yes --dbfilename magpie.rdb --save 300 1 --timeout 0
    volumes:
      - data-redis:/data
    networks:
      - magpie-network
    restart: always
  magpie_app_1:
    env_file:
      - ./configs/env/app.env
    image: magpie
    build:
      context: ..
      dockerfile: ./Dockerfile
    depends_on:
      - magpie_redis
      - magpie_postgres
    networks:
      - magpie-network
    volumes:
      - migration-file:/magpie/magpie/apps/file/migrations
      - data-locale:/magpie/magpie/locale
      - log-uwsgi:/var/log/magpie
      - static-content:/magpie/magpie/static
      - media-content:/usr/share/magpie/media
    environment:
      MAGPIE_DATABASES_NAME: fileserver_db
      MAGPIE_DATABASES_TEST_NAME: fileserver_db_test
      MAGPIE_DATABASES_USER: file_admin
      MAGPIE_DATABASES_PASSWORD: KLclWoEl5BoDtQVsL8RB3HIhH
      MAGPIE_DATABASES_HOST: magpie_postgres
      MAGPIE_DATABASES_PORT: 5432
      MAGPIE_REDIS_HOST: redis://magpie_redis
      MAGPIE_REDIS_PORT: 6379
      MAGPIE_CACHE_DATABASE: 1
      MAGPIE_CACHE_PREFIX: fls
      MAGPIE_STATIC_URL: /static/
      MAGPIE_STATIC_DIRS: staticfiles
      MAGPIE_STATIC_ROOT: static
      MAGPIE_MEDIA_URL: /files/
      MAGPIE_MEDIA_ROOT: /usr/share/magpie/media
    restart: unless-stopped
  magpie_app_2:
    env_file:
      - ./configs/env/app.env
    image: magpie
    depends_on:
      - magpie_redis
      - magpie_postgres
    networks:
      - magpie-network
    volumes:
      - migration-file:/magpie/magpie/apps/file/migrations
      - data-locale:/magpie/magpie/locale
      - log-uwsgi:/var/log/magpie
      - static-content:/magpie/magpie/static
      - media-content:/usr/share/magpie/media
    environment:
      MAGPIE_DATABASES_NAME: fileserver_db
      MAGPIE_DATABASES_TEST_NAME: fileserver_db_test
      MAGPIE_DATABASES_USER: file_admin
      MAGPIE_DATABASES_PASSWORD: KLclWoEl5BoDtQVsL8RB3HIhH
      MAGPIE_DATABASES_HOST: magpie_postgres
      MAGPIE_DATABASES_PORT: 5432
      MAGPIE_REDIS_HOST: redis://magpie_redis
      MAGPIE_REDIS_PORT: 6379
      MAGPIE_CACHE_DATABASE: 1
      MAGPIE_CACHE_PREFIX: fls
      MAGPIE_STATIC_URL: /static/
      MAGPIE_STATIC_DIRS: staticfiles
      MAGPIE_STATIC_ROOT: static
      MAGPIE_MEDIA_URL: /files/
      MAGPIE_MEDIA_ROOT: /usr/share/magpie/media
    restart: unless-stopped
networks:
  magpie-network:
    driver: bridge
volumes:
  media-content:
  static-content:
  log-nginx:
  log-uwsgi:
  data-postgres:
  data-redis:
  data-locale:
  migration-file: